# Generated by Django 3.2 on 2021-04-15 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='password_owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='password',
            name='password_shared_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
