# Generated by Django 3.2 on 2021-04-25 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_app', '0002_auto_20210415_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password_shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
