# Generated by Django 3.2 on 2021-04-27 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_app', '0003_alter_password_password_shared_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password',
            options={'verbose_name': 'Hasło', 'verbose_name_plural': 'Hasła'},
        ),
        migrations.AlterField(
            model_name='password',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='password',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='password',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data wygaśnięcia'),
        ),
        migrations.AlterField(
            model_name='password',
            name='modify_date',
            field=models.DateField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=1000, verbose_name='Hasło'),
        ),
        migrations.AlterField(
            model_name='password',
            name='password_owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AlterField(
            model_name='password',
            name='password_shared_users',
            field=models.ManyToManyField(blank=True, related_name='_password_app_password_password_shared_users_+', to=settings.AUTH_USER_MODEL, verbose_name='Dziel hasło z'),
        ),
    ]
