# Generated by Django 3.2.6 on 2021-08-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_app', '0004_auto_20210427_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data wygaśnięcia (opcjonalnie)'),
        ),
    ]
